#!/bin/bash
# HEADER for Parallel job using 80 processors:
#SBATCH --nodes=1           # number of nodes
#SBATCH --exclusive
#SBATCH --ntasks-per-node=1    # number of processors per node
#SBATCH --cpus-per-task=1       # number of cpus per task
#SBATCH -t 148:00:00      # run for 3 hr max
#SBATCH --partition=ROME
##SBATCH --partition=crfel
###SBATCH --mail-type=begin   # send email when process begins...
###SBATCH --mail-type=end     # ...and when it ends...
###SBATCH --mail-type=fail    # ...or when it fails.
###SBATCH --mail-user=<your-email>@princeton.edu # send notifications to this email
#SBATCH -e job.err              # Name of output file for error messages
#SBATCH -o job.out              # Name of output file for standard output



# BODY - commands to be run
# Load required modules
. /scratch.nike/srini237/OpenFOAM/OpenFOAM-6/etc/bashrc
. /scratch.nike/srini237/OpenFOAM/OpenFOAM-6/user/bashrc
. /scratch.nike/srini237/OpenFOAM/OpenFOAM-6/user/etc/bashrc

#. /home/zhan6305/OpenFOAM/cleanOpenFOAM/OpenFOAM-6/etc/bashrc
#. /home/zhan6305/OpenFOAM/cleanOpenFOAM/OpenFOAM-6/user/bashrc
#. /home/zhan6305/OpenFOAM/cleanOpenFOAM/OpenFOAM-6/user/etc/bashrc
. /home/srini237/.bashrc

conda activate
python Datagen_N2_C6H14.py &> output
