#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2011-2018 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
#
#------------------------------------------------------------------------------



export FOAM_USER_DIR=$FOAM_DIR/user
export FOAM_USER_SRC=$FOAM_USER_DIR/src
export FOAM_USER_APPBIN=$FOAM_USER_DIR/platforms/$WM_OPTIONS/bin
export FOAM_USER_LIBBIN=$FOAM_USER_DIR/platforms/$WM_OPTIONS/lib
export FOAM_USER_PY=$FOAM_USER_DIR/platforms/$WM_OPTIONS/python
export FOAM_USER_PF=$FOAM_USER_DIR/ThirdParty/platforms
export PATH=$FOAM_USER_APPBIN:$FOAM_USER_PF/bin:$PATH
export LD_LIBRARY_PATH=$FOAM_USER_LIBBIN:$LD_LIBRARY_PATH

alias opr="cd $WM_PROJECT_DIR"

[ "$BASH" ] && . $FOAM_USER_DIR/etc/bash_completion