#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2011-2018 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
#
#------------------------------------------------------------------------------



#export FOAM_DIR=/work/07137/tg864362/frontera/OpenFOAM-6
export FOAM_DIR=$(cd $(dirname ${BASH_SOURCE:-$0})/.. && pwd -P)
export FOAM_PY_PATH=/home/zhy/anaconda3/envs/cantera/include/python3.8
#source $FOAM_DIR/etc/bashrc
#source $FOAM_DIR/user/etc/bashrc

source $FOAM_DIR/etc/bashrc;source $FOAM_DIR/user/etc/bashrc

alias ofo="source $FOAM_DIR/etc/bashrc;source $FOAM_DIR/user/etc/bashrc"
alias ofd="source $FOAM_DIR/etc/bashrc WM_COMPILE_OPTION=Debug;source $FOAM_DIR/user/etc/bashrc"
alias odwmake="source $FOAM_DIR/etc/bashrc;source $FOAM_DIR/user/etc/bashrc;wmake;source $FOAM_DIR/etc/bashrc WM_COMPILE_OPTION=Debug;source $FOAM_DIR/user/etc/bashrc;wmake"
